In [1]:
import numpy as np
import pandas as pd

In [11]:
arr1 = np.array([3, 6, 9])
arr1

array([3, 6, 9])

In [12]:
# returns the number of dimensions (axes) of an array
arr1.ndim

1

In [15]:
arr2 = np.array([[1, 2, 3], [4, 5, 6]])
arr2

array([[1, 2, 3],
       [4, 5, 6]])

In [16]:
arr2.ndim

2

In [36]:
# creates a 2D array with n rows and m columns, where all elements are initialized to 1.
arr3 = np.ones((3, 3))
arr3

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [37]:
# creates a 2D array with n rows and m columns, where all elements are initialized to 0.
arr4 = np.zeros((3, 3))
arr4

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [38]:
# generates a 2D array of shape (n, m) filled with random floating-point numbers uniformly distributed
random_arr = np.random.random((3, 3))
random_arr

array([[0.62494119, 0.4676075 , 0.49595733],
       [0.56627161, 0.36116469, 0.45872765],
       [0.25738541, 0.4108792 , 0.21631352]])

In [39]:
# creates a square 2D identity matrix of size n x n, where all the diagonal elements are 1 and the rest are 0.
identity_arr = np.identity(3)
identity_arr

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [32]:
# arrange = np.arange(5)  # returns the arranged array from 0 to n - 1
arrange = np.arange(5, 11)  # returns the arranged array from m to n - 1
arrange

array([ 5,  6,  7,  8,  9, 10])

In [40]:
# generates c evenly spaced numbers between a and b (inclusive).
linspace_arr = np.linspace(2, 10, 20)
linspace_arr

array([ 2.        ,  2.42105263,  2.84210526,  3.26315789,  3.68421053,
        4.10526316,  4.52631579,  4.94736842,  5.36842105,  5.78947368,
        6.21052632,  6.63157895,  7.05263158,  7.47368421,  7.89473684,
        8.31578947,  8.73684211,  9.15789474,  9.57894737, 10.        ])

In [52]:
# Slices the array arr1 from index 0 to 1 (excluding 2) with a step of 1.
arr1[0:2:1]

array([3, 6])

In [63]:
# create a one-dimensional array from a multi-dimensional array. It returns a copy of the original array in a flattened (1D) form.
arr2.flatten()

array([1, 2, 3, 4, 5, 6])

In [67]:
# used to modify the shape of an array in-place.
arr2.resize(3, 2)
arr2

array([[1, 2],
       [3, 4],
       [5, 6]])